const test=require('node:test'),assert=require('node:assert/strict');
const {create,KEY,rankInfo}=require('../progression.js');
const chase=require('../chase.js');
function memory(){const data=new Map();return {data,getItem:key=>data.get(key)??null,setItem:(key,value)=>data.set(key,value)};}
test('no early mission flood; rewards persist and cannot be awarded twice',()=>{const s=memory(),p=create(s);assert.equal(p.update({hits:10},{steps:10,combo:10}).reward,0);assert.equal(p.update({hits:140}).reward,8);const q=create(s);assert.equal(q.update({hits:1}).reward,0);assert.equal(q.state.gems,8);p.flush();q.flush();});
test('record missions use maximum rather than repeated HUD sums',()=>{const p=create(memory());assert.equal(p.update({}, {steps:100}).reward,8);assert.equal(p.update({}, {steps:100}).reward,0);assert.equal(p.update({}, {steps:10}).reward,0);p.flush();});
test('catch payout and mission payout accounted once',()=>{const p=create(memory());assert.equal(p.update({tiles:1},{},30).reward,30);assert.equal(p.update({tiles:1},{},5).reward,5);assert.equal(p.update({tiles:1},{},12).reward,17);assert.equal(p.state.gems,52);p.flush();});
test('unlock exact debit, owned free, reload and insufficient funds',()=>{const s=memory(),p=create(s);assert.equal(p.purchase('heroes','veno').reason,'funds');p.update({}, {},500);assert.equal(p.purchase('heroes','veno').price,450);assert.equal(p.state.gems,50);assert.equal(p.purchase('heroes','veno').price,0);assert.ok(create(s).state.heroes.includes('veno'));assert.equal(p.purchase('songs','audio/stutter.mp3').reason,'funds');assert.equal(p.purchase('songs','special-stage-01').reason,'unknown');});
test('failed writes rollback purchases',()=>{const s=memory(),p=create(s);p.update({}, {},500);s.setItem=()=>{throw Error('quota');};assert.equal(p.purchase('heroes','veno').reason,'storage');assert.equal(p.state.gems,500);assert.ok(!p.state.heroes.includes('veno'));p.flush();});
test('v1 save migrates wallet, prior claims, theme and selected hero',()=>{const s=memory();s.setItem(KEY,JSON.stringify({version:1,gems:80,earned:90,stats:{hits:200,steps:20,combo:15,rush:1,tiles:1},claimed:['hits-20','combo-10'],themes:['classic'],theme:'classic'}));s.setItem('neon-blade-character','veno');const p=create(s);assert.equal(p.state.gems,80);assert.ok(p.state.heroes.includes('veno'));assert.equal(p.update({hits:1}).reward,0);assert.equal(p.state.xp,0);p.flush();assert.equal(create(s).state.version,2);});
test('rank milestones unlock only selected songs and grant no duplicate level rewards',()=>{const s=memory(),p=create(s);assert.equal(p.state.songs.filter(x=>!x.includes('tutorial')).length,3);let r=p.awardXP(280);assert.equal(r.rank,3);assert.equal(r.reward,20);assert.ok(p.state.songs.includes('audio/neon_rush.mp3'));assert.ok(!p.state.songs.includes('audio/stutter.mp3'));assert.equal(p.awardXP(0).reward,0);assert.equal(create(s).state.xp,280);assert.equal(rankInfo(119).rank,1);});
test('corrupt saves are never overwritten',()=>{const s=memory();s.setItem(KEY,'{broken');const p=create(s);p.update({hits:150});p.awardXP(120);p.flush();assert.equal(s.getItem(KEY),'{broken');});
test('shopping gift grants exactly once, persists, preserves progress and rolls back failed storage',()=>{
 const s=memory(),p=create(s);p.update({}, {},25);p.awardXP(10);
 assert.equal(p.grantShoppingTest().amount,100000);assert.equal(p.state.gems,100025);assert.equal(p.state.xp,10);assert.equal(p.state.earned,25);
 const q=create(s);assert.equal(q.grantShoppingTest().amount,0);q.purchase('heroes','veno');assert.equal(q.state.gems,99575);
 assert.equal(create(s).grantShoppingTest().amount,0);
 const bad=memory(),b=create(bad);bad.setItem=()=>{throw Error('quota');};assert.equal(b.grantShoppingTest().ok,false);assert.equal(b.state.gems,0);assert.deepEqual(b.state.testGrants,[]);
});
